name:                servant-sample
version:             0.1.0.0
github:              "githubuser/servant-sample"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/servant-sample#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies: 
    - aeson
    - servant-server
    - servant
    - wai
    - warp
    - text
    - bytestring
    - attoparsec
    - blaze-html
    - blaze-markup
    - directory
    - time
    - mtl
    - string-conversions
    - lucid
    - http-media
    - base-compat
    - aeson-compat
 
executables:
  servant-sample-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - servant-sample
  servant-sample-client:
    main:                Main.hs
    source-dirs:         client
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - servant-sample
    - servant
    - servant-client
    - http-client
    - aeson
  servant-sample-apitype:
    main:                Main.hs
    source-dirs:         apitype
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aeson
    - servant-server
    - servant
    - wai
    - warp
    - text
    - bytestring
    - attoparsec
    - time
    - mtl
    - string-conversions
    - base-compat
    - aeson-compat
    - transformers
    - time
    - lucid
  servant-sample-server:
    main:                Main.hs
    source-dirs:         server 
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aeson
    - servant-server
    - servant
    - wai
    - warp
    - text
    - bytestring
    - attoparsec
    - blaze-html
    - blaze-markup
    - directory
    - time
    - mtl
    - string-conversions
    - lucid
    - http-media
    - base-compat
    - aeson-compat
  servant-sample-servanterror:
    main:                Main.hs
    source-dirs:         servanterror
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aeson
    - servant-server
    - servant
    - wai
    - warp
    - text
    - bytestring
    - attoparsec
    - blaze-html
    - blaze-markup
    - directory
    - time
    - mtl
    - string-conversions
    - lucid
    - http-media
    - base-compat
    - aeson-compat
  servant-sample-responseheader:
    main:                Main.hs
    source-dirs:         responseheader
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aeson
    - servant-server
    - servant
    - wai
    - warp
    - text
    - bytestring
    - attoparsec
    - blaze-html
    - blaze-markup
    - directory
    - time
    - mtl
    - string-conversions
    - lucid
    - http-media
    - base-compat
    - aeson-compat
  servant-sample-staticfile:
    main:                Main.hs
    source-dirs:         staticfile
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aeson
    - servant-server
    - servant
    - wai
    - warp
    - text
    - bytestring
    - attoparsec
    - blaze-html
    - blaze-markup
    - directory
    - time
    - mtl
    - string-conversions
    - lucid
    - http-media
    - base-compat
    - aeson-compat
  servant-sample-nestedapi:
    main:                Main.hs
    source-dirs:         nestedapi
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aeson
    - servant-server
    - servant
    - wai
    - warp
    - text
    - bytestring
    - attoparsec
    - blaze-html
    - blaze-markup
    - directory
    - time
    - mtl
    - string-conversions
    - lucid
    - http-media
    - base-compat
    - aeson-compat
 




tests:
  servant-sample-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - servant-sample
